name: Run Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 11-23 * * MON-FRI"

# We only want one instance of Renovate running at a time
concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Generate a github token
        id: generate-gh-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.CITYGEO_BOT_GH_APP_ID }}
          private-key: ${{ secrets.CITYGEO_BOT_GH_APP_PRIVATE_KEY }}
          owner: CityOfPhiladelphia
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          token: ${{ steps.generate-gh-app-token.outputs.token }}
          configurationFile: config.js
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|AWS_REGION|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)$"
        # See https://github.com/renovatebot/github-action?tab=readme-ov-file#environment-variables
        env:
          RENOVATE_MULESOFT_USERNAME: ${{ secrets.RTF_PULL_USERNAME }}
          RENOVATE_MULESOFT_PASS: ${{ secrets.RTF_PULL_PASSWORD }}
          # LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.CITYGEO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CITYGEO_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
